# Movie Recommendation System Configuration

# Model Settings
model:
  name: "all-MiniLM-L6-v2"
  batch_size: 32
  max_length: 256
  device: "auto"

# TF-IDF Settings
tfidf:
  max_features: 50000
  ngram_range: [1, 2]
  min_df: 1
  max_df: 0.95

# Feature Engineering
features:
  top_n_cast: 3
  top_n_keywords: 10
  include_director: true
  include_genres: true
  include_keywords: true

# Similarity
similarity:
  alpha: 0.5

opensearch:
  host: ""
  port: 443
  use_ssl: true
  index_name: "movies"
  http_auth_env: "OPENSEARCH_BASIC_AUTH"

# Recommendations
recommendations:
  default_k: 10
  min_similarity: 0.0
  use_mmr: false
  mmr_lambda: 0.5
  mmr_pool_size: 100

# Performance
performance:
  save_embeddings: true
  verbose: true

# Evaluation
evaluation:
  enabled: false
  test_movies: []
  metrics: ["precision@k", "diversity", "coverage"]

# Paths (can be overridden by CLI)
paths:
  output_dir: "outputs"
  models_dir: "models"

